name: Mirror to Codeberg

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup SSH with a passphrase
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.GIT_SSH_PRIVATE_KEY}}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo '#!/bin/sh' > ~/.ssh_askpass
          echo 'echo $SSH_PASSPHRASE' >> ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
      - name: Print ssh-add identities
        run: ssh-add -l
      - name: Mirror code
        uses: stewalec/mirror-action@v0.0.1
        with:
          REMOTE: "ssh://git@codeberg.org/stewalec/website.git"
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
          DEBUG: "true"
